// lib/quotes.ts
export const QUOTES: string[] = [
  "Small steps, big changes.",
  "Consistency beats intensity.",
  "One more rep, one more win.",
  "Strong today, stronger tomorrow.",
  "Your future self is watching.",
  "Discipline builds freedom.",
  "Make sweat your signature.",
  "Effort compounds like interest.",
  "Show up before you level up.",
  "Progress loves patience.",
  "Motion beats perfection.",
  "Your pace, your race.",
  "Win the next 60 seconds.",
  "Stack good days.",
  "Strength is a daily choice.",
  "You don’t find time—you make it.",
  "Be the reason you believe.",
  "Reps write the story.",
  "Hard is the point.",
  "Start where you stand.",
  "Goals need groceries and sleep.",
  "Lift the weight, lose the doubt.",
  "One habit at a time.",
  "Quality reps over ego reps.",
  "The bar tells the truth.",
  "Sweat is the receipt.",
  "Tiny PRs still count.",
  "Build engines, not excuses.",
  "Chase strong, not tired.",
  "Earn your endorphins.",
  "The grind is a gift.",
  "One session changes the week.",
  "Volume builds resilience.",
  "Rest is part of the program.",
  "Practice being proud later.",
  "Outwork yesterday’s you.",
  "You are what you repeat.",
  "Grit over mood.",
  "Be where your feet are.",
  "Recover like you train.",
  "Strength starts in the mind.",
  "Fail forward, then reload.",
  "Routine makes results.",
  "Add weight to your standards.",
  "You can do hard things.",
  "Don’t wait to feel ready.",
  "Respect the warm-up.",
  "Form first, PRs second.",
  "Sweat the process, not the scale.",
  "Train today so tomorrow is easier.",
  "Show up especially on average days.",
  "Keep promises to yourself.",
  "Strong is a side effect of consistent.",
  "Be the person who doesn’t quit.",
  "Micro wins, macro change.",
  "Your reps are votes for your identity.",
  "Confidence is built under the bar.",
  "Write the plan, lift the plan.",
  "Keep the main thing the main thing.",
  "Energy follows action.",
  "Move well before you move more.",
  "Stack reps, not reasons.",
  "Patience is progressive overload.",
  "Sore is a souvenir, not a strategy.",
  "You’re one choice from momentum.",
  "Outlast your excuses.",
  "Better every set.",
  "No zero days.",
  "Respect rest days.",
  "Lift for the life you want.",
  "Train your weaknesses kindly.",
  "Hard doesn’t mean hurried.",
  "Eat like your goals matter.",
  "A missed day isn’t a lost week.",
  "Tidy reps, tidy mind.",
  "Capacity grows quietly.",
  "Sweat clears the static.",
  "Strength is self-trust practiced.",
  "Load the bar with intention.",
  "Plan the work, enjoy the work.",
  "Your habits are your coach.",
  "Fuel the output you expect.",
  "Progress is a direction, not a dot.",
  "Effort ages well.",
  "Meet yourself at the rack.",
  "Less drama, more data.",
  "Make hard things normal.",
  "Keep your reps honest.",
  "Breathe, brace, believe.",
  "Lift like you mean it.",
  "The clock is not your critic.",
  "Warm-ups are investments.",
  "Show up messy if needed.",
  "Tiny hinges swing big doors.",
  "Slow is smooth; smooth is strong.",
  "The body becomes what you ask of it.",
  "Worry less, carry more.",
  "Your ceiling is consistency.",
  "Earn your tomorrow today.",
  "Uncomfortable is where you grow.",
  "Recovery is where gains cash in.",
  "Be stubborn about the plan.",
  "Make the gym your promise kept.",
  "Your standard sets your strength.",
  "Start now; adjust later."
];

// Deterministic “quote of the day” using a seed (e.g., userId + YYYY-MM-DD)
export function quoteOfTheDay(seed: string): string {
  // Simple hash
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  const idx = Math.abs(h) % QUOTES.length;
  return QUOTES[idx];
}
